# Generated by Django 4.2.14 on 2024-07-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languagecards', '0002_remove_card_categories_card_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='description',
        ),
        migrations.AddField(
            model_name='card',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
    ]
