# Generated by Django 4.2.14 on 2024-08-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languagecards', '0003_remove_card_description_card_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='pronunciation',
            field=models.TextField(blank=True, null=True, verbose_name='pronunciation'),
        ),
        migrations.AlterField(
            model_name='card',
            name='text1',
            field=models.TextField(blank=True, null=True, verbose_name='mother tongue'),
        ),
        migrations.AlterField(
            model_name='card',
            name='text2',
            field=models.TextField(blank=True, null=True, verbose_name='foreign language'),
        ),
    ]
