# Generated by Django 4.2.14 on 2024-08-07 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languagecards', '0005_card_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='language',
        ),
    ]
