# Generated by Django 4.2.15 on 2024-08-08 13:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('languagecards', '0006_remove_file_language'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('text2', 'user')},
        ),
    ]
