webpage_texts = [{
    't0': 'Nyelvváltás',
    'T0': 'kifejezés vár megtanulásra',
    't1': 'Nyelvi kártyák adminisztrációja',
    'T1': 'admin/languagecards/',
    't2': 'Teljes siker!',
    't3': 'Internetes hanganyag: ',
    't4': 'Vissza a nyitólapra',
    'T4': '/',
    't5': 'Ötletek',
    'T5': 'otletek',
    't6': 'Szóról szóra',
    'T6': '2',
    't7': 'Nyomtatásra',
    'T7': 'Mégsem',
    't8': 'HASZNÁLHATOD BÁRMIRE',
    'T8': 'szavazatok',
    't9': 'Szavazatok beírása/módosítása',
    'T9': 'admin/languagecards/vote',
    'ta': 'Alaphelyzetbe',
    'Ta': 'https://porgeto.hu/orokzold/',
    'tm': 'Az összes kártya szűretlenül',
    'Tm': 'all',
    'tx': 'Ötletek beírása/módosítása',
    'Tx': 'admin/languagecards/idea',
    }]
