webpage_texts = [{
    't0': '- nincs használatban -',
    'T0': 'Nyelvi kártyák',
    't1': 'Nyelvi kártyák adminisztrációja',
    'T1': 'admin/languagecards/',
    't2': 'Internetes kotta: ',
    't3': 'Internetes hanganyag: ',
    't4': 'Vissza a nyitólapra',
    'T4': '/',
    't5': 'Ötletek',
    'T5': 'otletek',
    't6': 'Tömör változat',
    'T6': '2',
    't7': 'Nyomtatásra',
    't8': 'Szavazatok',
    'T8': 'szavazatok',
    't9': 'Szavazatok beírása/módosítása',
    'T9': 'admin/languagecards/vote',
    'ta': 'A régi honlap',
    'Ta': 'https://porgeto.hu/orokzold/',
    'tm': 'Az összes kártya szűretlenül',
    'Tm': 'all',
    'tx': 'Ötletek beírása/módosítása',
    'Tx': 'admin/languagecards/idea',
    'ty': 'Tavaszi válogatás',
    'Ty': 'tavasziak',
    'tv': 'Nyári válogatás',
    'Tv': 'nyariak',
    'tw': 'Őszi válogatás',
    'Tw': 'osziek',
    'tz': 'Téli válogatás',
    'Tz': 'teliek',
    }]
